//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_staff
    {
        public int Staff_ID { get; set; }
        public string StaffName { get; set; }
        public string Qualification { get; set; }
        public string Salary { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public string Address { get; set; }
    }
}
